const productos = [
	{
        id: '1',
        imagen: '../assets/img/unas/unas1.jpg',
        tipo: 'unas',
		nombre: 'ESMALTE ROJO',
        marca: 'HYPE',
		precio: 4000,
	},
    {
        id: '2',
        imagen: '../assets/img/unas/unas2.jpg',
        tipo: 'unas',
		nombre: 'ESMALTE CARIBBEA',
        marca: 'HYPE',
		precio: 4000,
	},
    {
        id: '3',
        imagen: '../assets/img/unas/unas3.jpg',
        tipo: 'unas',
		nombre: 'ESMALTE CLEAR',
        marca: 'HYPE',
		precio: 4000,
	},
	{
        id: '4',
        imagen: '../assets/img/unas/unas4.jpg',
        tipo: 'unas',
		nombre: 'KIT ACRILIC GEL COMPLETO',
        marca: 'THUYA',
		precio: 130000,
	},
    {
        id: '5',
        imagen: '../assets/img/unas/unas5.jpeg',
        tipo: 'unas',
		nombre: 'SET DE PEDICURA',
        marca: 'TOP FASHION',
		precio: 2600,
	},
    {
        id: '6',
        imagen: '../assets/img/unas/unas6.jpg',
        tipo: 'unas',
		nombre: 'POLVO ACRILICO PREMIUM',
        marca: 'THUYA',
		precio: 28000,
	},
    {
        id: '7',
        imagen: '../assets/img/unas/unas7.jpg',
        tipo: 'unas',
		nombre: 'KIT GEL PAINT MODELO',
        marca: 'THUYA',
		precio: 42150,
	},
    {
        id: '8',
        imagen: '../assets/img/unas/unas8.jpg',
        tipo: 'unas',
		nombre: 'SPIDER GEL',
        marca: 'THUYA',
		precio: 90000,
	},
    {
        id: '9',
        imagen: '../assets/img/unas/unas9.jpg',
        tipo: 'unas',
		nombre: 'FINALIZADOR',
        marca: 'THUYA',
		precio: 17100,
	},


    {
        id: '10',
        imagen: '../assets/img/cabello/cabello1.jpg',
        tipo: 'cabello',
		nombre: 'SHAMPOO SUAVIZANTE',
        marca: 'RUSK',
		precio: 13500,
	},
    {
        id: '11',
        imagen: '../assets/img/cabello/cabello2.jpg',
        tipo: 'cabello',
		nombre: 'ACONDICIONADOR DEEPSHINE',
        marca: 'RUSK',
		precio: 15000,
	},
    {
        id: '12',
        imagen: '../assets/img/cabello/cabello3.jpg',
        tipo: 'cabello',
		nombre: 'SHAMPOO REPARADOR',
        marca: 'RUSK',
		precio: 26250,
	},
    {
        id: '13',
        imagen: '../assets/img/cabello/cabello4.jpg',
        tipo: 'cabello',
		nombre: 'ALISADO BRASILEÑO',
        marca: 'GLAUCI',
		precio: 9900,
	},
    {
        id: '14',
        imagen: '../assets/img/cabello/cabello5.jpg',
        tipo: 'cabello',
		nombre: 'ALISADO BRASILEÑO',
        marca: 'KATIVA',
		precio: 10499,
	},
    {
        id: '15',
        imagen: '../assets/img/cabello/cabello6.jpg',
        tipo: 'cabello',
		nombre: 'PERMANENTE',
        marca: 'HIPWETIN',
		precio: 17000,
	},
    {
        id: '16',
        imagen: '../assets/img/cabello/cabello7.jpg',
        tipo: 'cabello',
		nombre: 'TIJERAS ORIGINALES',
        marca: 'JAGUAR',
		precio: 223150,
	},
    {
        id: '17',
        imagen: '../assets/img/cabello/cabello8.jpg',
        tipo: 'cabello',
		nombre: 'PEINE PARA CORTE',
        marca: 'BABYLISS',
		precio: 2000,
	},
    {
        id: '18',
        imagen: '../assets/img/cabello/cabello9.jpg',
        tipo: 'cabello',
		nombre: 'PRENSA PICO',
        marca: 'BURMAX',
		precio: 900,
	},


    {
        id: '19',
        imagen: '../assets/img/maquillaje/maquillaje1.jpg',
        tipo: 'maquillaje',
		nombre: 'BASE MAQUILLAJE',
        marca: 'PALLADIO',
		precio: 16500,
	},
    {
        id: '20',
        imagen: '../assets/img/maquillaje/maquillaje2.jpg',
        tipo: 'maquillaje',
		nombre: 'PRIMER',
        marca: 'ARDELLBEAUTY',
		precio: 18500,
	},
    {
        id: '21',
        imagen: '../assets/img/maquillaje/maquillaje3.jpg',
        tipo: 'maquillaje',
		nombre: 'CORRECTOR',
        marca: 'ARDELLBEAUTY',
		precio: 8950,
	},
    {
        id: '22',
        imagen: '../assets/img/maquillaje/maquillaje4.jpg',
        tipo: 'maquillaje',
		nombre: 'RUBOR PRECIOUS',
        marca: 'PALLADIO',
		precio: 9300,
	},
    {
        id: '23',
        imagen: '../assets/img/maquillaje/maquillaje5.jpg',
        tipo: 'maquillaje',
		nombre: 'BRONZER',
        marca: 'ARDELLBEAUTY',
		precio: 9500,
	},
    {
        id: '24',
        imagen: '../assets/img/maquillaje/maquillaje6.jpg',
        tipo: 'maquillaje',
		nombre: 'ILLUMINADOR',
        marca: 'PALLADIO',
		precio: 10950,
	},
    {
        id: '25',
        imagen: '../assets/img/maquillaje/maquillaje7.jpg',
        tipo: 'maquillaje',
		nombre: 'PALETA SOMBRAS',
        marca: 'PALLADIO',
		precio: 15400,
	},
    {
        id: '26',
        imagen: '../assets/img/maquillaje/maquillaje8.jpg',
        tipo: 'maquillaje',
		nombre: 'MASCARA DE PESTAÑAS',
        marca: 'ARDELLBEAUTY',
		precio: 12900,
	},
    {
        id: '27',
        imagen: '../assets/img/maquillaje/maquillaje9.jpg',
        tipo: 'maquillaje',
		nombre: 'LABIAL',
        marca: 'ARDELLBEAUTY',
		precio: 10250,
	},
   
    
];